### PR TITLE
InitMangoGroup basic test

### PR DESCRIPTION
**Pull request by kevlubkcm**
Very simple test that sets up the bare minimum in order to run the `InitMangoGroup` instruction. Will be a stepping stone for more complicated tests

### CODE REVIEW

**Comment by mschneider** [comment]
Could you provide instructions how to run the tests in the top-level readme?

**Comment by mschneider** [comment]
I also get a bunch of build errors, when running the tests with `cargo t`. This is one of them:

```
error: `core::num::<impl u8>::next_power_of_two` is not yet stable as a const fn
   --> /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/fixed-1.7.0/src/macros_no_frac.rs:896:41
    |
896 |                           Self::from_bits(self.to_bits().next_power_of_two())
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/fixed-1.7.0/src/lib.rs:497:1
    |
497 | / fixed! {
498 | |     "An eight-bit fixed-point unsigned",
499 | |     FixedU8(u8, LeEqU8, "8", "7", "6", "5", "4"),
500 | |     1, "0x12", "0x12", "[0x12]", "[0x12]",
...   |
503 | |     FixedU16, u16, True
504 | | }
    | |_- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by kevlubkcm** [comment]
Will update readme. 

Strange. `cargo t` works fine for me. Do you have rust nightly enabled? 
```
    Finished test [unoptimized + debuginfo] target(s) in 0.23s
     Running unittests (target/debug/deps/mango-9fba5d9cb4e13638)

running 1 test
test processor::srm_token::test_id ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/test_init.rs (target/debug/deps/test_init-f43dcfdccfce7ee2)

running 1 test
[2021-04-29T13:10:12.098789043Z INFO  solana_program_test] "mango" program loaded as native code
[2021-04-29T13:10:12.263048653Z DEBUG solana_runtime::message_processor] Program log: Mango: InitMangoGroup
test test_init ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.37s

   Doc-tests mango

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by kevlubkcm** [comment]
actually, what version of rust do you have? seems like that specific error is with rust version < 1.50

**Pull request merged**
